version: '3.1'
services:
 api:
  build:
    context: ./api
 database:
    build:
     context: ./database
     dockerfile: db.Dockerfile
    restart: unless-stopped
    ports: 
      - "33060:3306"
    environment:
      MYSQL_DATABASE: qbsql
      MYSQL_USER: qbsql
      MYSQL_PASSWORD: "152535"
      MYSQL_ROOT_PASSWORD: "152535"
    volumes:
       - ./volumes/data:/var/lib/mysql
