version: '3.1'
services:
 api:
  build:
    context: ./api
  restart: unless-stopped
  ports:
    - "8080:8080"
  environment:
    LISTEN_ADDR: ":8080"
    DB_CONNECTION: "qbsql:152535@database/qbsql?parseTime=true"
 database:
    build:
     context: ./database
     dockerfile: db.Dockerfile
    restart: unless-stopped
    ports: 
      - "33061:3306"
    environment:
      MYSQL_DATABASE: qbsql
      MYSQL_USER: qbsql
      MYSQL_PASSWORD: "152535"
      MYSQL_ROOT_PASSWORD: "152535"
    volumes:
       - ./volumes/data:/var/lib/mysql
